export const WELCOME = 'WELCOME';
export const REDEEM_DISCOUNT = 'REDEEM_DISCOUNT';
export const REDEEM_DISCOUNT_SUCCESS = 'REDEEM_DISCOUNT_SUCCESS';
export const REDEEM_DISCOUNT_ERROR = 'REDEEM_DISCOUNT_ERROR';
